# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.find_BMU <- function(X, W, nBMU = 2L, nAnnoyTrees = 50L, QuantType = "hard", parallel = TRUE) {
    .Call(`_AnnoyVQRecall_find_BMU`, X, W, nBMU, nAnnoyTrees, QuantType, parallel)
}

.Recall_BMU <- function(nW, BMU, QE, ACT, parallel = TRUE) {
    .Call(`_AnnoyVQRecall_Recall_BMU`, nW, BMU, QE, ACT, parallel)
}

.RecallLabels_BMU <- function(XL, RF, BMU, ACT, parallel = TRUE) {
    .Call(`_AnnoyVQRecall_RecallLabels_BMU`, XL, RF, BMU, ACT, parallel)
}

